

---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: lualatex  
    toc: true
    toc_depth:  4   
    keep_tex:  true
    keep_md:   true
  header-includes:  
    -  \usepackage{helvet}  
    -  \renewcommand{\familydefault}{\sfdefault}  
    -  \usepackage{ulem}
fontsize: 10pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  skeleton
---
~/code/MASTER_INDEX.md

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "      ##",
  tidy = "styler",
  error = TRUE,
  collapse = T
) # T easier to read
```

```{r library 		}
library(data.table)
``` 

```{r example}
DT <- data.table(
  x = rep(c("b", "a", "c"), each = 3),
  y = c(1, 3, 6),
  v = 1:9
)

X <- data.table(
  x = c("c", "b"),
  v = 8:7,
  foo = c(4, 2)
)
DT
#         x     y     v
#    <char> <num> <int>
# 1:      b     1     1
# 2:      b     3     2
# 3:      b     6     3
# 4:      a     1     4
# 5:      a     3     5
# 6:      a     6     6
# 7:      c     1     7
# 8:      c     3     8
# 9:      c     6     9

X
#         x     v   foo
#    <char> <int> <num>
# 1:      c     8     4
# 2:      b     7     2


# Goal:

DT[X, on = .(x, y <= foo)]
#         x     y     v   i.v
#    <char> <num> <int> <int>
# 1:      c     4     7     8
# 2:      c     4     8     8
# 3:      b     2     1     7
```

```{r test}
# better NAMES for columns
DT <- data.table(
  x = rep(c("b", "a", "c"), each = 3),
  y = c(1, 3, 6),
  z = 1:9
)
DT


X <- data.table(
  a = c("c", "b"),
  b = 8:7,
  c = c(4, 2)
)
# error
DT[X]


DT[X, on = .(x = a)]
#         x     y     z     b     c
#    <char> <num> <int> <int> <num>
# 1:      c     1     7     8     4
# 2:      c     3     8     8     4
# 3:      c     6     9     8     4
# 4:      b     1     1     7     2
# 5:      b     3     2     7     2
# 6:      b     6     3     7     2


# error
X[DT, on = .(x = a)]

# note differnces!
X[DT, on = .(a = x)]

DT[X, on = .(x = a, y <= c)]
#         x     y     z     b
#    <char> <num> <int> <int>
# 1:      c     4     7     8
# 2:      c     4     8     8
# 3:      b     2     1     7

DT[X, on = .(y <= c)]
#         x     y     z      a     b
#    <char> <num> <int> <char> <int>
# 1:      b     4     1      c     8
# 2:      b     4     2      c     8
# 3:      a     4     4      c     8
# 4:      a     4     5      c     8
# 5:      c     4     7      c     8
# 6:      c     4     8      c     8
# 7:      b     2     1      b     7
# 8:      a     2     4      b     7
# 9:      c     2     7      b     7

3 %% 2
DT[X, on = .(x = a, y = c)]
#         x     y     z     b
#    <char> <num> <int> <int>
# 1:      c     4    NA     8
# 2:      b     2    NA     7


DT[X, .(x, x, x), on = .(x = a, y = c)]


DT[X, .(x, y, z, a, b, c), on = .(x = a, y = c)]
#         x     y     z      a     b     c
#    <char> <num> <int> <char> <int> <num>
# 1:      c     4    NA      c     8     4
# 2:      b     2    NA      b     7     2

DT[X, .(x, y, z, a, b, c, x), on = .(x = a, y = c)]
#         x     y     z      a     b     c      x
#    <char> <num> <int> <char> <int> <num> <char>
# 1:      c     4    NA      c     8     4      c
# 2:      b     2    NA      b     7     2      b
```


```{r render, eval=FALSE, include=FALSE 	} 
output_dir <- Sys.getenv("OUTPUT_DIR")
output_dir

{
  # get file
  file <- "/home/jim/.config/nvim/templates/skeleton.Rmd"
  file <- normalizePath(file)
  file


  ## Ref only
  # the_dir  <- dirname(file)
  # file  <- basename(file)
  # file  <- file.path(the_dir, file)
}

rmarkdown::render(file,
  #                  output_format="html_document",
  output_format = "pdf_document",
  intermediates_dir = "./tmp",
  clean = F, # leave tmp files
  output_dir = output_dir
)
```

#### html ONLY (fonts)
```{r, results = 'asis',echo = F}
htmltools::h3("Test big font")
htmltools::h4("Test medium font")
htmltools::h5("Test smaller font")
```
`r htmltools::h3("Outside chunck")`
