
ISLR Chapter 3.6 - LAB

### Use multiple samples of Boston, training data
```{r}
library("MASS")
library("ISLR")
library("skimr")
library("broom")
```

### Boston, predict median house (medv), 12 predictors
```{r}
head(Boston)
?Boston
names(Boston)
dim(Boston) # [1] 506  14
```

### Training Data (TODO)
### Choose from 1:length(Boston) , each size = size, take K of these
### TODO:   use lapply
```{r}
size=10
rnumber = sample(x=1:nrow(Boston),size=size,  replace=FALSE)
rnumber
(sample_k = Boston[rnumber , c("lstat", "medv") ])
str(sample_k)
attributes(sample_k) ## includes $row.names (numbered)
```

### lm.fit
```{r}
fit  <- lm(medv ~ lstat, data=Boston)
```

# -----------------------------
### Compute important numbers
### summary(lm.fit)
### NOTES:  506 residuals
# -----------------------------
```{r}
summary(fit)

names(fit)
#  [1] "coefficients"  "residuals"     "effects"       "rank"         
#  [5] "fitted.values" "assign"        "qr"            "df.residual"  
#  [9] "xlevels"       "call"          "terms"         "model"        

## fit$coef
    fit$coefficients
# (Intercept)       lstat 
#       34.55       -0.95 

## sum of square residuals
    sum( (fit$residuals)^2 )            # 19,472

## model, df of medv, lstat
    if (F) fit$model  

## confi Inter
    confint(fit)
#             2.5 % 97.5 %
# (Intercept) 33.45 35.659              # CI for B0   
# lstat       -1.03 -0.874

## predictions:
predict(fit, data.frame(lstat = c(5,10,15)), interval = "confidence")
#    fit  lwr  upr
# 1 29.8 29.0 30.6
# 2 25.1 24.5 25.6
# 3 20.3 19.7 20.9

## includes irreducible error
predict(fit, data.frame(lstat = c(5,10,15)), interval = "prediction")
#    fit   lwr  upr
# 1 29.8 17.57 42.0
# 2 25.1 12.83 37.3
# 3 20.3  8.08 32.5
```
## fails
```{r}
dev.new()
plot(fit)
dev.off()
```

###     Plot data + regression line
```{r}
attach(Boston)
plot(lstat, medv)
# NULL
abline(fit, lwd=3, col="red")
```

###  Plot 4,  residues do not look normal or same variance
```{r}
## set  paramaters, for 2 x 2 pltos
par(mfrow = c(2, 2))
plot(fit)

residuals(fit)

plot()

## residuals
## broom
b = broom::augment(fit)
plot(b$lstat, b$.resid)

```








