---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.5in,top=0.25in   
TAGS:  glue
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE)
library(glue)
```



### Why glue:: ?
  *   less need to use paste0
  *    saves couple of keystrokes, but easier to read
```{r glue}
x  <- 3
y   <- 4

paste0("x= ", x)
paste0("y= ", y)

glue("x= {x}\n")

```


```{r file_name}
glue("name of this file is {knitr::current_input()}\n")
output_file  <- knitr::current_input()
```


```{r invisible}

g  <- function(x) {
   list(x=x, a=2*x)
}
f  <- function(x) {
  invisible(list(x = x, a = 2*x))
}

g(2)  # prints the list

f(2)   # nothing prints!

ans  <- f(2)
ans   # prints the list

```



```{r knit_exit()} 
knitr::knit_exit()
```

\newpage

```{r render, eval=FALSE, include=F	} 
file  <- "00002_glue.Rmd" 

file  <- here("rmd", file)
file

output_file  <- ""


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  #output_format = "html_document",
                  output_format=c("html_document",    # if want both
                                  "md_document"),
                  output_dir = "out",
                  output_file = output_file)
                  #output_file = "out")
```
