---
title:  "`r knitr::current_input()`"  
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"   
output:   
  html_document:  
    code_folding: show
    #code_folding: hide
    toc: true 
    toc_depth: 2
    toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
    fontsize: 11pt   
    geometry: margin=0.5in,top=0.25in   
---

knitr functions (pdf): https://cran.r-project.org/web//packages/knitr/knitr.pdf

knitr home:  https://yihui.org/knitr/ and various sections
source code:  https://github.com/yihui/knitr/tree/master/R

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE   ) # FALSE  easier to read
library(knitr)
```
```{r TAGS, eval=TRUE, echo=FALSE}
this_file  <- knitr::current_input()
TAGS <- c("collapse", "chunks", "examples", this_file)

cat(paste0("This file: ", this_file) )
cat("TAGS: \n\n")
TAGS

```

```{r all_labels}
print(knitr::all_labels())
```

### regex patterns to parse chunks
```{r knitr_functions}
knitr::knit_patterns$get()
knitr::knit_patterns$set(my.name="jim")
knitr::knit_patterns$get()
```

### retrieve TAGS
```{r}
knitr::knit_patterns$get(label == "TAGS")
```


### find labels which match criteria
```{r get_TAGS }
t  <- knitr::all_labels(label == "TAGS")
t
```

### Return all possible patterns
```{r patterns, include=FALSE}
all_patterns
```

### Return R code for specified `label`
```{r get_code}
label  <- "TAGS"
knitr::knit_code$get(label)
```



```{r end}
knitr::knit_exit()
```



```{r render, eval=FALSE, include=FALSE}

# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root


file  <- here("rmd", "00065B_knitr_pkg_functions.Rmd")

file
# in general, pdf will look nicer
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  output_format = "html_document",
#                  output_file="out")
                  output_file = "~/Downloads/print_and_delete/out")

```
