---
title: "066_fs_examples.Rmd"
output:
  pdf_document:
    extra_dependencies: ["booktabs"]
    toc: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

 =====================
kable examples, including some latex
=====================
*  For regex, see 0032
Using regex, stringr to gather knitr chuncks
Neatly rename the chunks!

```{r include=FALSE }
knitr::opts_chunk$set(echo = TRUE, comment = "")
library(here)
library(fs)
library(lubridate)
library(magrittr)
library(tibble)
library(dplyr)
```

print current dir, clean up time
```{r}
knitr::opts_chunk$set(echo= TRUE, include= TRUE)

# dir_info, capture as_tibble
# convert Positct date-time to simple date

t <- as_tibble(dir_info()) %>% 
  mutate(modification_time = lubridate::as_date(modification_time)) %>% 
  select(path, size, modification_time )
print(t, n=500)
```

get names of files in rmd
```{r get_files}
# Remove path info with path_file() 
t <- as_tibble( fs::dir_info(here("rmd"))) %>% 
  mutate(path = fs::path_file(path),
    modification_time = lubridate::as_date(modification_time)) %>% 
	select(path, size, modification_time )

t
```



```{r include=FALSE}

kable(cbind(dt), "latex", booktabs = T) %>%
kable_styling(latex_options = c("striped", "scale_down"))
```

#### file listing
```{r include=FALSE}

# dir_info, capture as_tibble

# convert Positct date-time to simple date
t <- as_tibble(dir_info()) %>% 
  mutate(modification_time = lubridate::as_date(modification_time)) %>% 
	select(path, size, modification_time )


# ---- Working ----
kable(cbind(t), "latex", booktabs = T, longtable=T) %>%
kable_styling(latex_options = c("striped", "scale_down"))

```

add latex to kable?
```{r include=FALSE}
# print(t, n=500)

# DEFAULT:  
# custom <-c('', '', '', '', '\\addlinespace') 

# FAILDD  
#custom <-c('','\\addlinepace')

# customH <-  c("", "", "\\hline", "\\addlinespace")
# customH <-  c("", "", "\\")

# customH <- if (booktabs) c('', '', '', '', '\\addlinespace') else '\\hline'

# ------- Working ------
customH <-  c("", "", c("\\hline","\\addlinespace"))

# longtable insures table completely prints
kable(cbind(t), "latex", 
      booktabs = T, 
      #longtable = TRUE, 
      linesep = customH  ) %>%
kable_styling(latex_options = c("striped", "scale_down"))

```

#### 3rd way
```{r }
kable(cbind(t), "latex", 
      booktabs = T, 
      #longtable = TRUE, 
      linesep = "\\addlinespace"  ) %>%
kable_styling(latex_options = c("striped"))
```

kable
```{r example}
library(kableExtra)

dt <- mtcars[1:5, 1:6]
kable(dt, "latex")

# with booktabs ?)
kable(dt, "latex", booktabs = T)

kable(dt, "latex", booktabs = T) %>% 
kable_styling(latex_options = "striped")

# double space - nope
kable(mtcars[1:8, 1:4], "latex", booktabs = T, linesep = "\n") %>%
kable_styling(latex_options = "striped", stripe_index = c(1,2, 5:6))

```

```{r include=FALSE}

kable(cbind(dt), "latex", booktabs = T) %>%
kable_styling(latex_options = c("striped", "scale_down"))
```
```{r}
knitr::knit_exit()

```

