---
title: "`r knitr::current_input()`"  
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"   
output:   
  html_document:  
    code_folding: hide
    toc: true 
    toc_depth: 2
    toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
    fontsize: 11pt   
    geometry: margin=0.5in,top=0.25in   
---

## knitr::   functions


knitr functions (pdf): https://cran.r-project.org/web//packages/knitr/knitr.pdf
knitr home:  https://yihui.org/knitr/ and various sections
source code:  https://github.com/yihui/knitr/tree/master/R

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE   ) # FALSE  easier to read
library(knitr)
```


### knitr::current_input()
```{r current_input }
this_file  <- knitr::current_input() 
print(this_file)

this_file  <- knitr::current_input(dir = TRUE)
print(this_file)
``` 

```{r TAGS, eval=TRUE, echo=FALSE}
this_file  <- knitr::current_input()
TAGS <- c("collapse", "chunks", "examples", this_file)
print(paste0("This file: ", this_file) )

print("TAGS: ")

TAGS
```

### save TAGS
```{r save_TAGS}
knitr::knit_patterns$set(tags_label = TAGS)
```


### retrieve TAGS
```{r}
knitr::knit_patterns$get(label == "tags_label")
```

## all_labels()
```{r begin}
print(knitr::all_labels())
```

### regex patterns to parse chunks
```{r knitr_functions}
knitr::knit_patterns$get()
knitr::knit_patterns$set(my.name="jim")
knitr::knit_patterns$get()
```



### find labels which match criteria
```{r get_TAGS }
t  <- knitr::all_labels(label == "TAGS")
t
```

### Return all possible patterns
```{r patterns, include=FALSE}
all_patterns
```

### Return R code for specified chunk `label`
```{r get_code}
label  <- "TAGS"
knitr::knit_code$get(label)
```


## inline_expr("1+1")
```{r incline_expr}

inline_expr("1+1", "html")
inline_expr("1+1", "md")
inline_expr("1+1")  # knitr guesses from context
```


### knit_engines
```{r knit_engines}
names(knitr::knit_engines$get())
```

### knit_expand/embed R code
```{r knit_expand}
r  <- 2
knitr::knit_expand(text = 'Area of circle radius {{r}} is {{pi*r^2}}')
```



```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```

\newpage



```{r render, eval=FALSE	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root


file  <- here("rmd", "00065_knitr_pkg_functions.Rmd")
file
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  output_format = "html_document",
                  output_file = "out")
```





