---
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  pdf_document: 
    latex_engine: xelatex
toc: TRUE 
toc_depth:  1 
fontsize: 12pt 
geometry: margin=0.5in,top=0.25in 
TAGS:  base,sprint,gsub,regex
---

## base:: files and dir commands
## Collect HERE
### (Except package commands:  see 0088)
### Includes, base commands to rename files in directory.


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```

###base:: commands (why use fs:: ?)
```{r begin}
# the_dir  <- "~/mp3/from_youtube/"
the_dir  <- "~/mp3_files"
pat  <-  "^_[:digit:]{5}"

# mp3 files only, R requires \\ to create literal
pat  <- "\\.mp3$"
list.files(the_dir, pattern=pat)


# files in this project
list.files("./rmd", pattern="*.Rmd")
list.files("./rmd", full.names = TRUE ,pattern="*.Rmd")

if (FALSE)
  # file.rename()
  # file.create()
  # basename()
  # dirname()
  #
  # file.copy(from, to, overwrite = recursive, recursive = FALSE,
  #               copy.mode = TRUE, copy.date = FALSE)
  # list.dirs()
  # dir()
```


WOKRING CODE 
special case
* pat  =  "^_[[:digit:]]{5}"

```{r works}

if (FALSE ) {
  pat  <-  "^_[[:digit:]]{4,6}"
  pat  <-  "^_"
  pat <- `"^_00056"`

  pat <- "^_[[:digit:]]{5}"
}

```


### Example:  Use gsub to rename mp3 files
```{r special, eval=F,  include=F}

the_dir  <- "~/mp3_files"
# the_dir  <- "~/Downloads/mp3/from_youtube/"
the_dir
list.files(path = the_dir)

list.files(path = the_dir, pattern = pat)
old <- list.files(path = the_dir, pattern = pat)
old
new  <- gsub(pattern = pat, replace="_", x = v)
new

old  <- paste0(the_dir,old)
old


new  <- paste0(the_dir,new)
new

file.rename(
            from = old, 
            to = new)

```


### prepend
```{r prepend_file_name}
prepend  <- "0"
old  <- list.files("./rmd", pattern="*.Rmd")
new  <- paste0(prepend, old)
```

### sprintf has some nice features!
```{r sprint}
sprintf("hello %s", "jim")

sprintf("hello %s", 23)

sprintf("hello %04s", 23)         # min of 4
sprintf("hello %04f", 23)         # 23.000000

sprintf("hello %04i", 23)         # int, min of 4 digits

```

regex, sub(), gsub will work
stringr is easier?
```{r}
the_dir  <- "./rmd"
the_files  <- list.files(the_dir)
the_files
library(stringr)
# regex
the_prefixes  <- stringr::str_extract(the_files, "^[0-9]*[A-Z]?_" )
the_prefixes

```


```{r knit_exit()} 
knitr::knit_exit() 
```

\newpage

```{r render, eval=FALSE	} 
file  <- "rmd/00086_base_file_commands.Rmd"
file


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  #output_format = "html_document",
                  output_format=c("html_document",    # if want both
                                  "md_document"),
                  output_dir = "out",
                  output_file = "out")
```
