---
title: "085_system_tools.Rmd"
output:  
  pdf_document:
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
fontsize: 12pt
---

 includes:  021_efficient_coding	

```{r setup}
knitr::opts_chunk$set(echo = TRUE, comment = "        ..##")
knitr::current_input()  # NUL
library(tibble)
library(tidyr)
library(purrr)
library(dplyr)
library(magrittr)
```
```{r tidyverse}
# anything out-of-date?
tidyverse::tidyverse_update()

# list packages  .. anything to remove?
devtools::session_info(c("tidyverse"))
```

```{r mem}
mem_used()/1e6
xfun::is_unix()
```
system.time vs proc.time()
```{r system.time}
# returns dbl[3]
system.time( r  <- rnorm(1000))
  {
    begin  <- proc.time()
    r  <- rnorm(1000)
    end  <- proc.time() - begin
    end
  }
```

ENV variables
```{r}
# /usr/lib/R
(r_home <-R.home(component="home"))
Sys.getenv("R_HOME") 			# /usr/lib/R ; where R installed
Sys.getenv("R_LIBS_USER") # ~R/x86 .../4.0
Sys.getenv("R_HIST_SIZE")
Sys.getenv("R_BROWSER")   # croutonurlhandler

# too lengthy
if  (FALSE) Sys.getenv()		

# search(), vector: gives all env + attached pkgs
(t_search <- search())
```
find package locations
```{r pkg_location}
base::system.file(package="base")
base::system.file(package="tibble")
```

```{r .libPaths)
#### 4-.libPaths(), list all paths, purpose, name
#### see also ~/.Renviron

t_libPaths <- tibble(.libPaths()) %>% 
  mutate(
  purpose =  c("added packages", 
               ".Library.site", 
               ".Library.site", 
               "base R pkgs"),  

  quantity  = c("many", "Empty", "Empty", "many")  ,
  env_var = c("R_LIBS_USER","","","R_LIBS?"),
  aka = c("",".Library.site", ".Library.site", ".Library.site, .Library"))

t_libPaths
```

other ways to list all pkgs
```{r all_pkgs}
# too much output
if (FALSE) {
  #### another way to list ALL pkgs
  # For each element of .libPaths(), dir() returns list of ALL files/directories.
  lapply(.libPaths(), dir)   # dir() returns <list>

  #### returns <list> of char[]	
  lapply(.libPaths(), list.dirs, recursive = FALSE)
}

```

```{r .Rprofile}
file.exists(
  file.path(r_home, 
  "etc", 
  "Rprofile.site")
)	

file.exists("~/dotfiles/.Rprofile")                     # TRUE
file.exists("~/.Rprofile")
```

.Renviron
```{r .Renviron}
file.exists(file.path(r_home, "etc", "Renviron.site"))  # TRUE,empty
file.exists("~/dotfiles/.Renviron")                     # TRUE
file.exists("~/.Renviron")                     # TRUE

```
TODO
options()
```{r options}
# options() (returns <list>)
# Tibble 87 x 2.  values is list-column.
# Goal:  longer tibble, with 1 row for each value

l  <- options()
# find TRUE


l2  <- purrr::discard(l, ~is_function(.x))
l2
l3   <- purrr::discard(l2, ~(typeof(.x) == "language"))
length(l3)

l3[31:40]
l  <- l3
t <- tibble(name = names(l), values = l)
map(t$values, ~typeof(pluck(1)))
t$typeof  <- typeof(pluck(t$values, 1)) 
head(t)

# Problem, options()[[5]] is 'closure' and not a vector, list.
t %>% tidyr::unchop(values)

options() %>% dplyr::filter(rlang::is_list(values))


typeof(options()[[5]])
t %>% unchop(values)


typeof(pluck(t,2,1))
typeof(pluck(t,2,2))
typeof(pluck(t,2,5))
pluck(t,2,5)
pluck(t,2,10, 1)
pluck(t,2,10, 1)

#### TODO
t %>% tidyr::unnest_wider(options)
tidyr::unnest_auto(t, options)

#### another way
l  <- options()
names(l) #88

#### find element of vector
l["warning.length"]
l["pdfviewer"]	  # /usr/bin/xdg-open
l["keep.source"]  # TRUE
l["browser"]	 # croutonurlhandler

```

Versions
```{r versions}

packageVersion("rmarkdown") # 1.10
R.version.string     # 3.5.1
getwd()                 # ~/code/r_
list.files()            # list filesin wd
dir()
```
Dependncies
TODO:   utils::depends(pkg =  c(), dependencies=c ())
```{r dependencies}

# For each installed pkg, find its dependencies
#### return list of character vectors, ~15,293 
	
l <- tools::package_dependencies(
							"tibble",
							db=installed.packages(),
							reverse=TRUE	)
l

# And "tibble" is dependenat upon:
l <- tools::package_dependencies("tibble", reverse=FALSE)
str(l) # named list, 1 elemnt named tibble,  a chr[12]
l

t  <- tibble(pkg=l$tibble)
t
##### 010-for <pkg>, find packages dependent upon it
```

```{r remove_package}
if (FALSE) remove.packages("cellranger")

#### BEGIN HERE!

######  011_update all packages - 
# available.packages()  	# A LOT!

# uncomment (takes time)
# update.packages(ask = FALSE, repos = 'https://cran.r-project.org')


###### 012_update knitr
install.packages('knitr', repos = c('https://xran.yihui.name', 'https://cran.r-project.org'))


##### 013_jennyBC
####  from https://github.com/smithjd/explore-libraries/blob/master/01_explore-libraries_jenny.R
ipt <- installed.packages() %>%
  as_tibble()

ipt %>% glimpse()
nrow(ipt)
dim(ipt)

####' 014_Exploring the packages

####   * tabulate by LibPath, Priority, or both
#### base: 14, recommended:15, my library:165
ipt %>%
  count(LibPath, Priority)

####   * what proportion need compilation?
####   2nd line produces 3 rows x 2 (NeedCompliation n)
ipt %>%
  count(NeedsCompilation) %>%
  mutate(prop = n / sum(n))

#### 015_remove pkg
# uninstall()  vs remove.packages() ??
#### Find (and remove) package BH (it is gone!)
ipt %>% filter(Package=="BH") 

uninstall(BH)

#### 016_Internactive session?
base::interactive() #### TRUE (run a line at a time) 

#### 017_R_LIBS_USER
Sys.getenv("R_LIBS_USER")

#### OR, 1st element of 
.libPaths()

#### 018_List all files in project/pkg
#### current dir
base::dir()
base::dir(recursive = TRUE)  #### recurse directories
base::dir(all.files = TRUE)	 #### include hidden

#### examine project (source) directory
base::dir(path = "../r_mp3_files/", all.files = TRUE)	 #### include hidden

base::dir(path = "../r_mp3_files/", all.files = TRUE, recursive = TRUE)	 #### includ directories 
```


R help
```{r}
# REF https://csgillespie.github.io/efficientR/set-up.html

?mpg   # mpg is dataset (if loaded)
?stats  # package
?reprex # function
?ggplot   # function
??reprex  # topic
??ggplot   # topic 
??pch      # topic 
??regression

help.search("pch")  # long form


# returns named named chr[]: attr(l, "names")
l  <- Sys.info()  # Linux 4.4.52 - ....
t  <- tibble(name = names(l),
							value = l)


list.files(all.files = TRUE) # show hidden too

# ---- 001 monitor -----
# BIG

elements <- 1e8   # 1e9 and laptop crashes, rebootsS
X <- as.data.frame(
        matrix(rnorm(elements), nrow=elements/10)
)

r1 <- lapply(X,median)

r2 <- parallel::mclapply(X, median)

```

```{r update_packages}

# ---- 002 update  all R packages ----
#update.packages(ask = FALSE)


# ----  003 view all installed R packages? ----
# at cmd line  which needed?
# apt-get cache search "^r-*" | sort

```

```{r startup}

# ---- 004 R startup ----

# In this order, R seeks .Rprofile $R_HOME, $HOME, project directory
?Startup
R.home() # /usr/lib/R
site_path = R.home(component = "home") # /usr/lib/R
fname = file.path(site_path, "etc", "Rprofile.site") # /usr/lib/R/etc/Rprofile.site

file.exists(fname) # True
```

```{r Rprofile}

file.exists("~/.Rprofile") # True, also

options()
# 2 sign digits  (3.7)
options(prompt = "R> ", digits = 2, show.signif.stars = FALSE, continue = "  ")

getOption("repos")  # cran.rstudio.com

fortunes::fortune(50)  # error
.Last = function() {
        
        message("Goodbye at ", date(), "\n")
}
.Last()
```
```{r from_tan}
library(tidyverse)
l <- options() %>% 
  list() %>% 
  tibble() %>% 
  unnest_longer(1,indices_to = "option",values_to = "value")
l
```
```{r enframe}
library(tibble)
library(purrr)
options()
# list  -> nested tibble?
t  <- tibble::enframe(options())
head(t)

l  <- map(t$value, ~typeof(.))
l[41:60]
c   <- map_chr(t$value, ~typeof(.))
c
# add column for typeof
t$c  <- c
head(t)

# examine t$value[[5]] # closure
t$value[[5]]


# make it expr
z  <- rlang::expr(t$value[[5]])
# return original state 
eval(z)

# easier?
get_typeof  <- function(o) {
  typeof(o)}
get_typeof("a")
get_typeof(z)
get_typeof(t$value[[5]])
get_typeof(function(x) {x})  # closure

map_chr(t$value, ~get_typeof(.))


#
# define process!
# process  <- function(type){
#   if (type == logical)
#   if (type == closure)
#     ...
# 
 
map(t$value, ~process)
t$value[[1]]
```


