
---
title:  "`r knitr::current_input() `"
date:  !r lubridate::today()
output: 
  pdf_document:
    toc: TRUE 
    toc_depth: 2
    latex_engine: xelatex
  html_document:  
    code_folding: show
    toc: true 
    toc_depth: 2
    toc_float: true
fontsize: 12pt
geometry: margin=0.4in,top=0.25in
params:
  date: !r lubridate::today()
TAGS:  reprex,rank
---

file="/home/jim/.config/nvim/templates/skeleton.R"

```{r rank}

# RANK is each element's distance from lowest (smallest) bottom (=1)
# 10 is always 3rd from bottom (which is 1 here)
rank(c(10, 8, 1))  # 3, 2, 1
rank(c(10, 8, 3))
rank(c(1,10,8))

```



```{r reprex}

# R
reprex::reprex( style= T, venue = "slack", x=

               {
#'  **Order vs rank**
                 #'
#'  The function roll() picks 3 letters (from the first 10) and displays results several ways.   
#'
#'  Every now and then order and rank do not match, puzzling me.   
#'



#'  First, the roll function                
    roll  <- function(original = NULL) {

    # if user provides no original, pick sample  of 3
    if (is.null(original))
      original  <- sample(letters[1:10], size=3)

    #  
    list  <- list(original = original, 
                  sort = sort(original),
                  order = order(original),
                  rank = rank(original)
                  )

    }
#' 
#'  # let's try, examine the different ways to present:
    #
    (r  <- roll())
#'

#' Now, try with this specific choice, why do order and rank differ? 
#'
    (r  <- roll(c("j", "d", "i")))
#'
    #'
})
```

```{r render, eval=F, include=F}

## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?
here()
file  <- "00100_base_rank.Rmd"
file  <- here("rmd", file)
file


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github
rmarkdown::render(file,
                  #output_format = "pdf_document",
#                 output_format = "html_document",
                  output_format=c("html_document",    # if want both
                                  "md_document"),
                  output_dir = "out",
                  output_file = "out")
```
