
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.5in,top=0.25in   
TAGS:  data.table,lapply,sum
---

## 00293_ Basic_Examples of DT

REF: https://stackoverflow.com/questions/32276887/use-of-lapply-sd-in-data-table-r
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
library(data.table)
```

### create dt
```{r begin}
set.seed(10238)
# A and B are the "id" variables within which the
#   "data" variables C and D vary meaningfully

create_dt  <- function () {
DT = data.table(
  A = rep(1:3, each = 5L), 
  B = rep(1:5, 3L),
  C = sample(15L),
  D = sample(15L)
)
return(DT)
}

dt  <- create_dt()
dt
```



### Count, sum columns, groupings
```{r}

#Sum all columns
dt[ , lapply(.SD, sum)]
#     A  B   C   D
# 1: 30 45 120 120
```

### Raw Markdown?
```{r testing, results="asis"}
###  Sum all columns
dt[ , lapply(.SD, sum)]
```

### Count Rows
```{r  resume}
dt[ , lapply(.SD, length)]
```
### By grouping, sum all, except A
```{r except}
dt[ , lapply(.SD, sum), by = A]
#    A  B  C  D
# 1: 1 15 38 43
# 2: 2 15 30 49
# 3: 3 15 52 28
```
###Sum all columns EXCEPT A
```{r except3}
dt[ , lapply(.SD, sum), .SDcols = !"A"]
```

### Group on A, count
```{r count2}
dt[ , lapply(.SD, length), by = A]
```
```{r complex}

#Sum all columns EXCEPT A, grouping BY B
dt[ , lapply(.SD, sum), by = B, .SDcols = !"A"]
#    B  C  D
# 1: 1 27 29
# 2: 2 17 30
# 3: 3 33 11
# 4: 4 23 36

dt[ , lapply(.SD, length), by = B, .SDcols = !"A"]

# Count, each combination of c("A", "B")
dt[ , lapply(.SD, length), by = c("A","B")]
```

### normalize - votes
```{r votes}
# each=2, each element repeated twice, before moving on.
votes <- function() {
  data.table(issue = rep(c("issue1", "issue2"),times=1, each=2),
             A = rep(c("Y",NA), 2),
             B = rep(c(NA,"N"),2)
             )
}
dt = votes()
dt
```

```{r}
dt  <- votes()
dt_A  <- dt[!is.na(A), .(country = "A", vote=A), by = issue]
dt_A
dt_B  <- dt[!is.na(B), .(country = "B", vote=B), by = issue]
dt_B

```

***

```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```


```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file:
#   where dir is relative to project root

{
file  <-"rmd/00293_DT_practice_examples.Rmd" 
file  <- basename(file)
file  <- here("rmd", file)
file
}

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# in general, pdf will look nicer
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  #output_format = "html_document",
                  output_format = "md_document",
                  output_dir = "md",
                  #output_file = here("out","out")
                  )
```
