---
title: "066_fs_examples.Rmd"
output:
  pdf_document:
    extra_dependencies: ["booktabs"]
    toc: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

DUPLICATE?
REMOVE?


 =====================
Rename:  knitr chunks
=====================
*  Other regex, see 0032
Using regex, stringr to gather knitr chuncks
Neatly rename the chunks!

```{r include=FALSE }
knitr::opts_chunk$set(echo = TRUE, comment = "")
library(here)
library(fs)
library(lubridate)
library(magrittr)
library(tibble)
library(dplyr)
```

print current dir, clean up time
```{r}
knitr::opts_chunk$set(echo= TRUE, include= TRUE)

# dir_info, capture as_tibble
# convert Positct date-time to simple date

t <- as_tibble(dir_info()) %>% 
  mutate(modification_time = lubridate::as_date(modification_time)) %>% 
  select(path, size, modification_time )
print(t, n=500)
`'`

get names of files in rmd
```{r get_files}
# Remove path info with path_file() 
t <- as_tibble( fs::dir_info(here("rmd"))) %>% 
  mutate(path = fs::path_file(path),
    modification_time = lubridate::as_date(modification_time)) %>% 
	select(path, size, modification_time )

t
```


```{r}
knitr::knit_exit()

```

