<!--
	 vim:linebreak:nowrap:nospell:cul tw=78 fo=tqlnr foldcolumn=3 
-->	 
--- 
# Spaces, no Tabs
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  pdf_document: 
    latex_engine: xelatex
toc: TRUE 
toc_depth:  1 
fontsize: 12pt 
geometry: margin=0.5in,top=0.25in 
---

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```

```{r library, include=FALSE		}
library(jimTools) 
``` 


dput:  
```{r dput}
test <- data.frame(x = 1, y = 1)
test
typeof(test)  # list

# structure
output <- dput(test) # output is to console
output
typeof(output)  # list

# write structure to file
if (FALSE )
  dput(test, "junk.txt")


# capture.output()
v  <- capture.output(dput(test))
v  
typeof(v) # char[]

# collapse to single ch[]
paste0(v, collapse="/n")


# function?
# as chr[] vector
capture.output(dput(paste0))

# single chr[]
s  <- paste0(capture.output(dput(paste0)), collapse = "/n")
s

```

```{r dput_expr}
z  <- expr(dput(test))
z
c  <- eval(z)
```

***

```{r knit_exit()} 
knitr::knit_exit() 
```

/newpage

```{r render, eval=FALSE	} 
file <- "" 
file  <- basename(file) 
dir <-"rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```
