
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  typeof
---


### Try to collect info re:  base R types,  that is all.
### R basic types
  *  REF:  [hadley Chapter 12]( https://adv-r.hadley.nz/base-types.html )

#### (from help) unlikely to be seen at user level 

  *    symbol, 
  *    pairlist, 
  *    promise,
  *    language, 
  *    char, 
  *    ..., 
  *    any, 
  *    expression, 
  *    externalptr,
  *    bytecode 
  *    weakref  

(Stole from maya?)
::: WIP, construct an assorted list of `typeof` objects :::



```{r typeof} ex  <- list( `[`, `[[`, `c`, `+`, sum, c(1,2), c(TRUE,FALSE), function(x) {x+1},  "abcd", environment())

g  <- function(x) { 
  # Given an unevaluated expression, deparse returns char[1] 
  paste(deparse(x), "=", typeof(x))
}

purrr::map(ex, g)

lapply(ex, g)


```
### Pairlist
  *  Ref Adv-R Chapter 18.6
  *  Similar to named lists, but ...
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
```


```{r library 		}
# print all labels
file  <- knitr::current_input() 
print(knitr::all_labels())
library(jimTools)
``` 


```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```

\newpage


```{r skeleton}
file="/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer


## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?

{
file  <- "" 
file  <- basename(file)
file  <- here("rmd", file)
file
}


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github

rmarkdown::render(file,
    #output_format = "pdf_document",
    #output_format = "html_document",
    output_format=c("html_document", "md_document"),
    #output_dir = "out",
    output_file = "out")

# ==========================================
#  Example 1:  pdf| same name as source file | in wd |
# ==========================================

rmarkdown::render(file,
    output_format = "pdf_document")

# ============================================================
#  Example 2:  pdf | same name as source file | in pdf/|
# ============================================================
# pdf/  will be created

if (knitr::is_latex_output())  (
rmarkdown::render(file
    output_format = c("pdf_document") ,
    output_dir = "pdf")
)

if (knitr::is_html_output()) (

rmarkdown::render(file,
    output_format = c("html_document", "md_document"), 
    output_dir = "html")

)
```
