--- 
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  html_document
#   pdf_document: 
#     latex_engine: xelatex
#     toc: TRUE 
#     toc_depth:  4 
fontsize: 10pt 
geometry: margin=0.5in,top=0.25in 
---

## Simple latex
## Works in both .pdf and .html
### rmarkdown knows to use math_jax for html
REF: https://gist.github.com/derekmcloughlin/896da22518ef2f3d81b0
<!-- 
set cul   "cursorline
cc=+1			"colorcolumn is 1 more than tw

vim: to format all urls for md
s/https.*/[&]()/g
-->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE)
```

<!--  RENDER:  see bottom -->

```{r library, include=FALSE		}
library(jimTools)
``` 

$\sum x_{i}$
```{r begin}
```
### Independent Samples

$$\mu_{\bar{x_{1}} - \bar{x_{2}}} = \mu_{1} - \mu_{2}$$


#### Standard Errors

$$s_{e} = \sqrt \frac {SSResid}{n - 2}$$
***

```{r knit_exit()} 
knitr::knit_exit()
```

/newpage

```{r render, eval=FALSE	} 
# here() is useless
# how to easily change R direcctory,  WHEN I can vim's ?

setwd("~/code/r_try_things_here")
getwd()

file <- "0200_math_latex.Rmd"
file  <- basename(file)
dir <- "rmd"

rmarkdown::render(here(dir, file), 
                  output_dir="~/Downloads/print_and_delete/")
```
