
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  sprintf, glue, paste0, vectorize, sQuote, eval
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # easier to read
library(jimTools)
library(glue)
```


```{r library 		}
# print all labels
file  <- knitr::current_input() 
print(knitr::all_labels())
``` 


### Both sprint and glue offer improved over print 
  *  REF:  [Glue](https://www.r-bloggers.com/2019/07/glue-magic-part-i/)

### sprintf:
  * sprintf(x, FORMAT)
  * wrapper for os command

```{r sprint}
sprintf("hello %s", "jim")
sprintf("hello %s", 23)
sprintf("hello %04s", 23)         # min of 4
sprintf("hello %04f", 23)         # 23.000000
sprintf("hello %04i", 23)         # int, min of 4 digits

# five digits,  great for prefix!
  N  <- 10 
  sprintf("%05i", 1:N)


  sprintf("This is e= %2d", exp(1))
  sprintf("This is exponential %02e", 1000)


```

### sprintf examples from help
```{r from_help}
     sprintf("%f", pi)
     sprintf("%.3f", pi)   # 3 decimal places
     sprintf("%1.0f", pi)
     sprintf("%5.1f", pi)
     sprintf("%05.1f", pi)
     sprintf("%+f", pi)
     sprintf("% f", pi)
     sprintf("%-10f", pi) # left justified
     sprintf("%e", pi)
     sprintf("%.3e", pi)  # 3 digits
     sprintf("%E", pi)
     sprintf("%g", pi)
     sprintf("%g",   1e6 * pi) # -> exponential
     sprintf("%.9g", 1e6 * pi) # -> "fixed"
     sprintf("%G", 1e-6 * pi)
```


### Why glue:: ?
  *   less need to use paste0
  *    saves couple of keystrokes, but easier to read
```{r glue}
x  <- 3
y  <- 4

paste0("x = ", x)
paste0("y = ", y)

glue("x = {x}\n")

```

### Glue can also hold r expressions/functions
```{r file_name}

## trival
  glue("1 + 1 = {1+1}")

## nope:
  glue("name of this file is {knitr::current_input()}\n")
  output_file  <- knitr::current_input()


## cute, prepend number to each file name in the directory
  l  <- list.files(".")
  glue("{1:length(l)}_{l}")


## sprintf + glue ?  
## Format prefix with zeros   (00001_file_name)
  prefix  <- sprintf("%04i", 1:length(l))
  glue("{prefix}_{l}")
```

#### glue and sQuote
```{r sQuote}
x  <- 55

## Compare
  glue("value of {sQuote(quote(x))} is {x}")
  # value of ‘x’ is 55

  glue("value of {quote(x)} is {x}")
  # value of x is 55

# NOTE:
sQuote(x)
# [1] "‘55’"

quote(x) # supress eval
# x

```


### paste0 is vectorized; don't overlook
```{r paste0, attr.source='.numberLines'}
c1  <- letters[1:10]
c2   <- 1:length(c1)

paste0(c1, " = ", c2)


c3  <- sprintf("%04i", c2)
c3

paste0(c3, " = ", c1)
paste0(c3, "_", c1)

```

### print line numbers (pdf only?)
```{r, attr.source='.numberLines'}
if (TRUE) {
  x <- 1:10
  x + 1
}
```

```{r invisible}

g  <- function(x) {
   list(x=x, a=2*x)
}
f  <- function(x) {
  invisible(list(x = x, a = 2*x))
}

g(2)  # prints the list

f(2)   # nothing prints!

ans  <- f(2)
ans   # prints the list
```


```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```


```{r skeleton}
file="/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer


## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?

{
file <- "/home/jim/code/try_things_here/rmd/6000_glue_sprintf_examples.Rmd"
file  <- basename(file)
#file  <- here("rmd", file)
file  <- paste0(file.path("~/code/try_things_here/"),"rmd/", file)
file
}

output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

rmarkdown::render(file,
                  output_format = "pdf_document",
                  output_dir = output_dir)


```
