---
TAGS:  github_actions, fake YAML
---
The quickest way to get a GitHub Actions template for rendering a document is
to grab this example action from r-lib which renders generic readme file. The
below line initializes the file and renames it for editing.

# create yaml file
```{r yaml, eval=F, include=F}
  args(usethis::use_github_action)

## fails
  usethis::use_github_action(name = "render-readme.yaml")

## works, but creates ./github and files withi
  usethis::use_github_action(name = "render-rmarkdown.yaml")
```

# rename to render a generic doc
```{r rename, eval=F, include=F}

from  <-
  file.path("~/code/try_things_here/.github/workflows/render-rmarkdown.yaml")
to  <- 
  file.path("~/code/try_things_here/.github/workflows/skeleton.yaml")

file.copy(from = from, to= to, overwrite=F)

if (F) {
fs::file_move(
  here::here(".github/workflows/render-readme.yaml"),
  here::here(".github/workflows/render-doc.yaml")
)
}
```

We then edit the .yaml in session:
```{r edit}

#  usethis::edit_file('.github/workflows/render-doc.yaml')


```

You can view the resulting file within the repo, but for ease of reading:
```

on:
  push:
    paths:
      - docs/my-document.Rmd

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("docs/my-document.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/my-document*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

```
