---
title: "index.Rmd page"
date: 2021-07-27
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  4   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS: try_things_here 
---
~/code/MASTER_INDEX.md

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "      ##",
  error = TRUE,
  collapse = T
) # T easier to read
```

### print line numbers (pdf only?)
```{r, attr.source='.numberLines'}
if (TRUE) {
  x <- 1:10
  x + 1
}
```

```{r library 		}
library(jimTools)
``` 


```{r skeleton, include=F, eval=F}
file <- "/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 
output_dir <- Sys.getenv("OUTPUT_DIR")
output_dir

{
  file <- ""
  file <- basename(file)
  file <- here("rmd", file)
  file
}




## replacement for here
if (F) {
  the_dir <- dirname(file)
  file <- file.path(the_dir, file)
}
```
