---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: lualatex  
    toc: true
    toc_depth:  4   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  kable, kableExtra
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

### PURPOSE:   Demonstrate kableExtra works with data.table
kable, also works with data.table
```{r example}
library(data.table)
library(kableExtra)

#   to access mp3 filenames
library(mp3)
library(jimTools)

dt <- mtcars[1:5, 1:6]
kable(dt, "latex")

# output latex code;   with booktabs ?)
kable(dt, "latex", booktabs = T)

kable(dt, "latex", booktabs = T) %>% 
  kable_styling(latex_options = "striped")

# double space - nope
kable(mtcars[1:8, 1:4], "latex", booktabs = T, linesep = "\n") %>%
kable_styling(latex_options = "striped", stripe_index = c(1,2, 5:6))

```

```{r include=FALSE}
kable(cbind(dt), "latex", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down"))
```
```{r print_mp3_file_names}
## limit ,  kable chokes on Unicode characters
dt  <- mp3:::get_file_names()[1:300]
kableExtra::kbl(dt) |> group_rows(start_row = 1, end_row=300, latex_wrap_text=T ) |> column_spec(1:2, width = "1cm")



```

```{r knitr::knit_exit(), include = FALSE  } 
knitr::knit_exit()
```

\newpage


```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{

file <- "/home/jim/code/try_things_here/rmd/00630_kable_examples.Rmd"
file  <- normalizePath(c(".", file))[[2]]
file
}

rmarkdown::render(file,
    output_format = "pdf_document",
    #output_format = "html_document",
    output_dir = output_dir)
)

```

```{r notes, eval=F, include=F}

##### NOTES
#  [For technical notes]: (~/docs/technical_notes/001_render_output.md)

# from ~/.Renviron
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer


## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?


# ==========================================
#  Example 1:  pdf| same name as source file | in wd |
# ==========================================

rmarkdown::render(file,
    output_format = "pdf_document")

# ============================================================
#  Example 2:  pdf | same name as source file | in pdf/|
# ============================================================
# pdf/  will be created

if (knitr::is_latex_output())  (
rmarkdown::render(file
    output_format = c("pdf_document") ,
    output_dir = "pdf")
)

if (knitr::is_html_output()) (

rmarkdown::render(file,
    output_format = c("html_document", "md_document"), 
    output_dir = "html")

)

```
# ---- Working ----
kable(cbind(t), "latex", booktabs = T, longtable=T) %>%
kable_styling(latex_options = c("striped", "scale_down"))
```{r include=FALSE}
# print(t, n=500)

# DEFAULT:  
# custom <-c('', '', '', '', '\\addlinespace') 

# FAILDD  
#custom <-c('','\\addlinepace')

# customH <-  c("", "", "\\hline", "\\addlinespace")
# customH <-  c("", "", "\\")

# customH <- if (booktabs) c('', '', '', '', '\\addlinespace') else '\\hline'


# ------- Working ------
customH <-  c("", "", c("\\hline","\\addlinespace"))

# longtable insures table completely prints
kable(cbind(t), "latex", 
      booktabs = T, 
      #longtable = TRUE, 
      linesep = customH  ) %>%
kable_styling(latex_options = c("striped", "scale_down"))

```

#### 3rd way
```{r }
kable(cbind(t), "latex", 
      booktabs = T, 
      #longtable = TRUE, 
      linesep = "\\addlinespace"  ) %>%
kable_styling(latex_options = c("striped"))
```
