---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  4   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  
---
~/code/MASTER_INDEX.md

### Using Monte Carlo to estimate area under curve:
  *  see Gillespie, Lovelace, pg 51-53 (2016)
  *  using vectorization

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "      ##",
  error = TRUE,
  collapse = T
) # T easier to read
```


#### Area under y=x^2  [0,1]
```{r area_}
## generate N random points in unit square (x, y)
N <- 10^4
x <- runif(N)
y <- runif(N)

## Now consider the curve y = x^2,
## That is, for each x consider x^2.   Compare this to actual y.

c <- x^2

##  We want to know fraction of points Below the curve, x^2 > y
##  Calculus :  1/3
A <- function(N) {
  mean(c > y)
}
A()
head(x)
head(c)
```

#### Try to calc e:   BS can't start with exp(-x) !
```{r area_}
## generate N random points in unit square (x, y)
N <- 10^4
x <- runif(N)
y <- runif(N)

## Now consider the curve y = e^(-x),
## That is, for each x consider e^-x.   Compare this to actual y.

c <- exp(-x)

##  We want to know fraction of points Below the curve, exp(-x) > y
##  Calculus :  value = 1/(1-A)
A <- function(N) {
  mean(c > y)
}
A()
value <- 1 / (1 - A())
value
# [1] 2.74
```



```{r render, eval=FALSE, include=FALSE 	} 
output_dir <- Sys.getenv("OUTPUT_DIR")
output_dir

{
  file <- ""
  file <- basename(file)
  file <- here("rmd", file)
  file
}




## replacement for here
if (F) {
  the_dir <- dirname(file)
  file <- file.path(the_dir, file)
}
```
