---
title: 
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---
## jsonlite:: package
REF:  https://arxiv.org/abs/1403.2805

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```

<!--  RENDER:  see bottom -->

```{r library, include=FALSE		}
library(jimTools) 
library(gh)
library(jsonlite)
```

```{r}
# GITHUB_PAT is set in ~/.Renviron
# to retrieve it:
gh::gh_token()
Sys.getenv("GITHUB_PAT")


owner <- "hadley"
repo <- "r-pkgs"
pr_list <-
  gh("/repos/:owner/:repo/pulls", owner = owner, repo = repo,
     .token=Sys.getenv("GITHUB_PAT"),
     state = "all", .limit = Inf)
length(pr_list)   #503


users <- gh("/users", .limit = 50)
length(users)

gh("/licenses")

gh("/users/jimrothstein")
gh("/users/jimrothstein/repos")

gh("/rate_limit")
```
use jsonlite  
```{r}
hadley_repos <- jsonlite::fromJSON("https://api.github.com/users/hadley/repos")

str(hadley_repos, max.level=1, vec.len=1      )
```

```{r }
apikey  <- Sys.getenv("API_KEY")
nj  <- jsonlite::fromJSON( 
paste0("http://www.opensecrets.org/api/?method=getLegislators&id=NJ&apikey=", 
       apikey, "&output=json"))
nj

# best choic
t  <- tibble::as_tibble(purrr::pluck(nj, "response", "legislator",
                                     "@attributes"))
t # 14 x 21
```
examine respons
```{r}
str(nj, max.level=1)
str(nj, max.level=2)
str(nj, max.level=3)
str(nj, max.level=4)
```


```{r}
knitr::knit_exit()

```
