---
title: "073_dplyr_vignette_window"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


rank (returns index) vs order (return permutation)
```{r}
rank(c(10, 20, 30, 40)) # 1 2 3 4
order(c(10, 20, 30, 40)) # 1 2 3 4

z <- c(40, 30, 20, 10)
rank(z) # 4 3 2 1
order(z) # 4 3 2 1  (ie 1->4)


a <- c(10, 20, 30, 40)
rank(desc(a)) # 4 3 2 1
order(desc(a)) # 4 3 2 1
```

```{r}
a <- c(10, 30, 20)
rank(a) # 1 3 2
order(a) # 1 3 2


a <- c(10, 40, 20, 30)
rank(a) # 1 4 2 3, use this order of indices to puts a in size order
order(a) # 1 3 4 2
```

```{r}
(r1 <- rank(x1 <- c(3, 1, 4, 15, 92)))
x2 <- c(3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5)
names(x2) <- letters[1:11]
(r2 <- rank(x2)) # ties are averaged

## rank() is "idempotent": rank(rank(x)) == rank(x) :
stopifnot(rank(r1) == r1, rank(r2) == r2)

## ranks without averaging
rank(x2, ties.method = "first") # first occurrence wins
rank(x2, ties.method = "last") #  last occurrence wins
rank(x2, ties.method = "random") # ties broken at random
rank(x2, ties.method = "random") # and again
```
