
---
title:   "017_metaprogramming.Rmd"
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

---
TODO -- replace title, dir etc with R expressions
comments
.

/home/jim/.config/nvim/templates/skeleton.Rmd
comments
---

<!--  commments -->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```

```{r library, include=FALSE} 
here()
library(jimTools)
```

Render
```{r render, eval=FALSE, echo=FALSE	}
p  <- fs::path()
w  <- fs::path_wd()
w
here()
file="017_metaprogramming.Rmd"
dir="book_advanced_R/R"

ren_pdf(file,dir)
ren_github(file, dir)

#knitr::knit_exit()

# To Render
ren_pdf  <- function(file, dir) {
rmarkdown::render(
									here( dir, file), 
									output_dir="~/Downloads/print_and_delete") 
}
ren_pdf(file, dir)

ren_github  <- function(file, dir) {
rmarkdown::render(
									here(dir, file) 
									output_format="github_document",
									output_dir="~/Downloads/print_and_delete") 
}
ren_github(file, dir)
```
rlang::expr | rlang::enexpr
```{r 17.2_code}
rlang::expr(a+b+10)
expr(some_fun(a))

capture_it  <- function(x) expr(x)
capture_it(a+b+10)  #x

capture_it2  <- function(x) enexpr(x)
capture_it2(a+b+10) # returns a+b+10 
capture_it2(caller_env())


# STUDY f
f  <- expr(f(x=1, y=2))
typeof(f)
class(f)
attributes(f)

f   # just its value
f[[1]]  # its name?
f[[2]]
f[[3]]

as_list(f)

# f[[4]]

```
lobstr::ast
```{r 17.3_code}

lobstr::ast(x+y)
lobstr::ast(f(x,y))
lobstr::ast(f(x, g(y)))

lobstr::ast(f(x, g(h(z)), h(z)))
ast( ff  <- expr(f(x,y)))

```

rlang::call2() create function (given a tree) 
```{r 17.4}
# must quote
rlang::call2("f", "y", "z")
rlang::call2("f", 1, 2	)


# inverse!
ast(call2("f", 1, 2	))

#
# error, nice try
# call2(ast(f(x,y)))
```

alternative to call2 to develop code, use !!  unquote
```{r 14.4_contiue}

# quote (makes expression?)
xx  <- expr(x+x) 
yy   <- expr(y + y) 

# create R code: (uquote expression?)
expr(!!xx/!!yy)

# inverse!
ff  <- expr(f(x,y))
expr(!!ff)


# create code

f  <- function(var){
	var  <- enexpr(var)  # capture
	expr(3*(!!var))  # do something, and capture this.
}
f(x)
f(x+y)
f(f(x))
f(1+3+x)

# Hadley's example:
cv <- function(var) {
  var <- enexpr(var)
  expr(sd(!!var) / mean(!!var))
}

```







