---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
---

REF:  https://jennybc.github.io/purrr-tutorial/ls01_map-name-position-shortcuts.html

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
file  <- knitr::current_input() 
print(knitr::all_labels())
library(jimTools)
library(purrr)
```

```{r got_chars}
C  <- got_chars
head(C)
# non-named list
names(C)
length(C) #30

# huge!
str(C, max.depth=1)
str(C, max.depth=1, vec.len=2)
str(C, max.depth=1, vec.len=0)

str(C, max.depth=0, vec.len=0)

```


```{r part2}
# subset of list
C[1:4]

str(C[1], max.depth=0, vec.len=0)

# this is useful, examine just the 1st element of C
str(C[[1]], max.depth=0, vec.len=0)



```

### name - wow
```{r name}
# return a list of 30, each element (a list) contain char[1]
purrr::map(C, "name")



# in base R?  YES!
get_name  <- function(e) {
   e$name
}
lapply(C, get_name)
```

### by position
```{r by_position}
purrr::map(C, 3)

get_name.2  <- function(e) {
  e[[3]]
}
lapply(C, get_name.2)

# works on subset of list C
lapply(C[1:3], get_name.2)
```

```{r exercise.1}
# For single character, get names of its list elements
# playby is 18th
names(C[[1]]) #18

```

### use map_chr instead of map
```{r}
# char[]
map_chr(C,"name") 


# in R?
unlist(lapply(C, get_name))
```
### TODO - NEXT, extract multiple values
```{r}
```







```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```

\newpage


```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer


## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?

{
file  <- "" 
file  <- basename(file)
file  <- here("rmd", file)
file
}


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github

rmarkdown::render(file,
    #output_format = "pdf_document",
    #output_format = "html_document",
    output_format=c("html_document", "md_document"),
    #output_dir = "out",
    output_file = "out")

# ==========================================
#  Example 1:  pdf| same name as source file | in wd |
# ==========================================

rmarkdown::render(file,
    output_format = "pdf_document")

# ============================================================
#  Example 2:  pdf | same name as source file | in pdf/|
# ============================================================
# pdf/  will be created

if (knitr::is_latex_output())  (
rmarkdown::render(file
    output_format = c("pdf_document") ,
    output_dir = "pdf")
)

if (knitr::is_html_output()) (

rmarkdown::render(file,
    output_format = c("html_document", "md_document"), 
    output_dir = "html")

)
```
