---
title: "Identify GENERICS and METHODS -- Issue 746"
date:  \today 
format:
  pdf: 
    include-in-header: 
      text: |
        \usepackage[top=.5in, bottom=.5in, left=.5in, right=.5in]{geometry}
        \usepackage{amsmath,amssymb,amstext,amsfonts}
        \usepackage{lipsum}
---


To run:	quarto render %	; zathura  

```{r get_started}
install.packages("easystats")
easystats::install_latest()
```


```{r}
library(easystats)
library(parameters)
library(broom)
library(glue)
library(magrittr)


# 346	
broom_tidy <- ls(getNamespace("broom"), pattern="^tidy[.]")
broom_tidy

data.frame(method=broom_tidy, is_S3 = sapply(broom_tidy, sloop::is_s3_method,
USE.NAMES=F)) 
                            method is_S3
 1                      tidy.aareg  TRUE
 2                        tidy.acf  TRUE
 3                      tidy.anova  TRUE
 4                        tidy.aov  TRUE
 5                    tidy.aovlist  TRUE
 6                      tidy.Arima  TRUE
 7                    tidy.betamfx  TRUE
 8                    tidy.betareg  TRUE
 9                      tidy.biglm  TRUE
 10                 tidy.binDesign  TRUE
 11                  tidy.binWidth  TRUE
 12                      tidy.boot  TRUE
 13                    tidy.btergm  TRUE
 14                       tidy.cch  TRUE
 15                 tidy.character  TRUE
 16                       tidy.cld  TRUE
 17                       tidy.clm  TRUE
 18                      tidy.clmm  TRUE
 19                  tidy.coeftest  TRUE
 20              tidy.confint.glht  TRUE
 21           tidy.confusionMatrix  TRUE
 22                     tidy.coxph  TRUE
 23                       tidy.crr  TRUE
 24                 tidy.cv.glmnet  TRUE
 25                tidy.data.frame  TRUE
 26                   tidy.default  TRUE
 27                   tidy.density  TRUE
 28                      tidy.dist  TRUE
 29                       tidy.drc  TRUE
 30          tidy.durbinWatsonTest  TRUE
 31                   tidy.emmGrid  TRUE
 32                  tidy.epi.2by2  TRUE
 33                      tidy.ergm  TRUE
 34                  tidy.factanal  TRUE
 35                      tidy.felm  TRUE
 36                  tidy.fitdistr  TRUE
 37                    tidy.fixest  TRUE
 38                    tidy.ftable  TRUE
 39                       tidy.gam  TRUE
 40                       tidy.Gam  TRUE
 41                     tidy.garch  TRUE
 42                    tidy.geeglm  TRUE
 43                      tidy.glht  TRUE
 44                       tidy.glm  TRUE
 45                    tidy.glmnet  TRUE
 46                    tidy.glmrob  TRUE
 47                    tidy.glmRob  TRUE
 48                       tidy.gmm  TRUE
 49                     tidy.htest  TRUE
 50                     tidy.ivreg  TRUE
 51                     tidy.kappa  TRUE
 52                       tidy.kde  TRUE
 53                   tidy.Kendall  TRUE
 54                    tidy.kmeans  TRUE
 55                    tidy.lavaan  TRUE
 56                tidy.leveneTest  TRUE
 57                      tidy.Line  TRUE
 58                     tidy.Lines  TRUE
 59                      tidy.list  TRUE
 60                        tidy.lm  TRUE
 61                   tidy.lm.beta  TRUE
 62                   tidy.lmodel2  TRUE
 63                     tidy.lmrob  TRUE
 64                     tidy.lmRob  TRUE
 65                   tidy.logical  TRUE
 66                  tidy.logitmfx  TRUE
 67                    tidy.lsmobj  TRUE
 68                    tidy.manova  TRUE
 69                       tidy.map  TRUE
 70                   tidy.margins  TRUE
 71                    tidy.Mclust  TRUE
 72                   tidy.mediate  TRUE
 73                       tidy.mfx  TRUE
 74                    tidy.mjoint  TRUE
 75                      tidy.mle2  TRUE
 76                       tidy.mlm  TRUE
 77                    tidy.mlogit  TRUE
 78                     tidy.muhaz  TRUE
 79                  tidy.multinom  TRUE
 80                    tidy.negbin  TRUE
 81                 tidy.negbinmfx  TRUE
 82                      tidy.nlrq  TRUE
 83                       tidy.nls  TRUE
 84                      tidy.NULL  TRUE
 85                   tidy.numeric  TRUE
 86                    tidy.orcutt  TRUE
 87            tidy.pairwise.htest  TRUE
 88                       tidy.pam  TRUE
 89                       tidy.plm  TRUE
 90                tidy.poissonmfx  TRUE
 91                     tidy.poLCA  TRUE
 92                      tidy.polr  TRUE
 93                   tidy.Polygon  TRUE
 94                  tidy.Polygons  TRUE
 95               tidy.power.htest  TRUE
 96                    tidy.prcomp  TRUE
 97                 tidy.probitmfx  TRUE
 98                    tidy.pyears  TRUE
 99                     tidy.rcorr  TRUE
 100                 tidy.ref.grid  TRUE
 101               tidy.regsubsets  TRUE
 102                  tidy.ridgelm  TRUE
 103                      tidy.rlm  TRUE
 104                      tidy.rma  TRUE
 105                      tidy.roc  TRUE
 106                       tidy.rq  TRUE
 107                      tidy.rqs  TRUE
 108                    tidy.sarlm  TRUE
 109                    tidy.Sarlm  TRUE
 110    tidy.SpatialLinesDataFrame  TRUE
 111          tidy.SpatialPolygons  TRUE
 112 tidy.SpatialPolygonsDataFrame  TRUE
 113                     tidy.spec  TRUE
 114                 tidy.speedglm  TRUE
 115                  tidy.speedlm  TRUE
 116              tidy.summary_emm  TRUE
 117             tidy.summary.glht  TRUE
 118               tidy.summary.lm  TRUE
 119              tidy.summary.plm  TRUE
 120           tidy.summaryDefault  TRUE
 121                 tidy.survdiff  TRUE
 122                  tidy.survexp  TRUE
 123                  tidy.survfit  TRUE
 124                  tidy.survreg  TRUE
 125                   tidy.svyglm  TRUE
 126                   tidy.svyolr  TRUE
 127                tidy.systemfit  TRUE
 128                    tidy.table  TRUE
 129                    tidy.tobit  TRUE
 130                       tidy.ts  TRUE
 131                 tidy.TukeyHSD  TRUE
 132                   tidy.varest  TRUE
 133                      tidy.zoo  TRUE

ls()

methods("tidy")

is.null(help("tidy.xyz", package = "broom"))
is.null(help("tidy.zoo", package = "broom"))
x

#	can't find method tidy.ts???
sloop::ftype(tidy.ts)


sloop::is_s3_method
# does not work (wants path)
devtools::missing_s3("broom")
devtools::missing_s3(".")

# T if method
sloop::is_s3_method("tidy.ts")
sloop::ftype(tidy.ts)
sloop::is_s3_method("tidy.z")
sloop::is_s3_method("xyz.t")
sloop::is_s3_method("t.test")



#	True, if generic
utils::isS3stdGeneric("tidy")

#	returns body if T, error otherwise
utils::getS3method("tidy", class="ts" )

#	returns NULL if F
utils::getS3method("tidy", class="xyz", optional=T)

#	still don't understand
exists("tidy.ts")
is.object("tidy.ts")

##	legacy
#	139 tidy.<classes>  methods
broom_tidy <- broom_tidy[grepl("^tidy", broom_tidy)]

#	classes only, 139
broom_supported <- gsub("^tidy.", "", broom_tidy)


# 923
easystats_tidy <- ls(getNamespace("parameters"))

# 159 model_parameters.<classes>
easystats_tidy <- easystats_tidy[grepl("^model_parameters", easystats_tidy)]

# 159 classes
easystats_supported <- gsub("^model_parameters.", "", easystats_tidy)

# 97 classes, exaample.  broom has `zoo` class, but easystats does not
broom_supported[!broom_supported %in% easystats_supported]

#	SAME
     "%w/o%" <- function(x, y) x[!x %in% y] #--  x without y

		 broom_supported %w/o% easystats_supported

```


Get all classes in `broom` but not yet in `parameters`
```{r}

x  <- 	 broom_supported %w/o% easystats_supported

```

Generate code to cut/paste into roxygen2 for documentation.
```{r assemble}

cat(vapply(x, 
	function(x) { paste0("#' @export\n", "model_parameters.",x, "  <- model_parameters.default\n\n")},
	  character(length = 1), 
		USE.NAMES=F)

)
```
