---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.5in,top=0.25in   
---

<!-- 
code_folding: hide   to turn off

set cul   "cursorline
cc=+1			"colorcolumn is 1 more than tw

vim: to format all urls for md
s/https.*/[&]()/g
-->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
```


```{r library, include=FALSE		}
library(R6)
``` 


```{r begin}

# Tags:   R6, new()
library(R6)

Person <- R6Class("Person",
		public = list(
									name = NULL,
									hair = NULL,
								  initialize = function(name = NA, hair = NA) {
									self$name <- name
									self$hair <- hair
								  self$greet()
								},
								set_hair = function(val) {
																self$hair <- val
												},
								greet = function() {
																cat(paste0("Hello, my name is ", self$name, ".\n"))
												}
								)
)

#	create instance, runs initialize
ann <- Person$new("ann","brown")

is.R6(ann)
# [1] TRUE



ann$hair
ann$name
ann$greet()
ann$initialize()  # reset to defaul!
ann$set_hair("blonde")
ann$hair
print(file)
```

```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

file  <- here("", "")
file   <- "0013_R6_intro.Rmd"
# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# in general, pdf will look nicer
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  output_format = "html_document",
                  output_file = "~/Downloads/print_and_delete/out")
```
