--- 
title: "/home/jim/code/try_things_here/VECTOR/0015_base_list_advanced_examples.Rmd"
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
  pdf_document: 
    latex_engine: xelatex
fontsize: 10pt 
geometry: margin=0.5in,top=0.25in 
TAGS:  vector,list,vapply,  
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```
#### Structure of Lists
  *  Purpose:  understand tree-like structure in each
  *  lapply works on content of each elment
  *  lapply(x, .f)  list( f(x[[1]]), f(x[[2]], ...

#### Simplest possible
```{r simplest}


##  SAME
L.1  <- list(letters[1:2])
# [[1]]
# [1] "a" "b"
# 
L.1  # one element



L.2  <- list(c("a", "b"))  # one element
# [[1]]
# [1] "a" "b"
# 

L.3  <- list(c(letters[1:2]))  #SAME
# [[1]]
# [1] "a" "b"
# 

## identity function
    id  <- function(e) e
    identical(L.1, lapply(L.1, id))

# [1] TRUE

identical(L.2, lapply(L.2, id))
# [1] TRUE

identical(L.3, lapply(L.3, id))
# [1] TRUE


## SAME

    L.1[[c(1,2)]]
    # [1] "b"
    L.2[[c(1,2)]]
    # [1] "b"
    L.3[[c(1,2)]]
    # [1] "b"

## SUBSET
    L.1[1]
    # [[1]]
    # [1] "a" "b"
    # 

## Contents of element 1
    L.1[[1]]
# [1] "a" "b"


    # 2nd element of character vector
    L.1[[1]][2]
# [1] "b"


one  <- function(e) e[1]
two  <- function(e) e[[1]]

# function apply to THIS element
L.1[[1]]

#### THIS is not clear
    lapply(L.1, one)
    # [[1]]
    # [1] "a"
    # 
    lapply(L.1, two)
    # [[1]]
    # [1] "a"
    # 

```


```{r render, eval=FALSE, include=FALSE 	} 
{
file <- "VECTOR/0014_base_list_examples.Rmd"
# file  <- here("VECTOR", file)
file
}

output_dir = "~/Downloads/print_and_delete"
# in general, pdf will look nicer
rmarkdown::render(file,
                  output_dir = output_dir,
                  #output_format = "pdf_document")
                  output_format = "html_document")

```
