---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  4   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  Reduce, dput, Filter
---
~/code/MASTER_INDEX.md

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

### print line numbers (pdf only?)
```{r, attr.source='.numberLines'}
if (TRUE) {
  x <- 1:10
  x + 1
}
```
#### Reduce
  *  Accepts function and applies repeditively (NOT recursively) to
    list 2 elments at a time.   Higher Order Function 
```{r reduce}
Reduce(`+`, c(1,2,3))
# [1] 6

## why is first term 1?
    Reduce(`+`, 1:9, accumulate=T)
    # [1]  1  3  6 10 15 21 28 36 45

## note
    seq_len(9)
    # [1] 1 2 3 4 5 6 7 8 9


Reduce("+", seq_len(9))
# [1] 45

Reduce("+", as.list(1:9))
# [1] 45

```

#### Reduce, with 2 variables

```{r reduce2}
v  <- c(1,2,3)
f  <- function(u,v) u+v

Reduce(f, v, accumulate=T)
# [1] 1 3 6
```


#### chain  of functions!
  *  see demo(Reduce)
```{r functions}
l  <- list(log, exp, acos, cos)
fun  <- function(f, ...) f(...)

## note: from right, ie init=0
Reduce(fun, x=l, init=0, right=T, accumulate=T)

```
```{r base}
baseenv()
ls(baseenv())  # lots!

formals(get)
funs <- Filter(is.function, sapply(ls(baseenv()), get, baseenv()
))

L  <- length(funs) #1242
L
```

#### find common elements
```{r genes}

v1 <- c("geneA","geneB")
v2 <- c("geneA","geneC")
v3 <- c("geneD","geneE","geneA")
v4 <- c("geneA","geneE")
v5 <- c("geneB","geneC","geneA")

Reduce(intersect, list(v1,v2,v3,v4,v5), accumulate=T)
```

```{r reduce_list}
z  <- list(
           list(2),
           list(-1),
           list(-3),
           list(4)
           )

f  <- function(u,v) unlist(u) + unlist(v)
Reduce(f,z, accumulate=T)
```

```{r reduce3}

create_w  <- function() {
w  <- list(
     a = list("A", 2),
     b = list("A", -1),
     c = list("B", -3),
     d = list("A", 4)
     )
}
w  <- create_w()
w

unlist(list("A", 2))[2]

## these work
    f  <- function(u,v) u[[2]] 
    sapply(w, f)

    h  <- function(e) e
    sapply(w, h)

##-----------------------------------------------------------
## can't get binary to work, ie extract number portion only
## EXPLAIN
    h  <- function(u,v) paste0(as.character(unlist(u)[1]) , as.character(unlist(v)[1]))
    ans  <- Reduce(h, w, accumulate=T)
    dput(ans)
##-----------------------------------------------------------


g  <- function(u,v) as.numeric(unlist(u)[[2]]) + as.numeric(unlist(v)[[2]])
Reduce(g, w, accumulate=T)
```

#### Filter a vector, dput
```{r reduce4}

## remove B entries 
    w  <- create_w()
    f  <- function(e) ifelse(e[[1]] == "A",e[[2]],0)

    ans  <- Filter(f, w)
    ans

## easier to understand with dput
    dput(ans)
```

#### Fibonaci?
```{r fib}

## 1,1,2,3,5,8,13,21
## can also begin 0,1,1,2...
i  <- 1:5

f  <- function(u,v) {
    if (u == 1 && v != 2) v  <- 1
    u + v
}
Reduce(f, i,accumulate=T)





}

g  <- function(i) g(i-1)+ g(i-2)

seq_len(9)
# [1] 1 2 3 4 5 6 7 8 9

ans  <- Reduce(g, seq_len(9), init=1   , accumulate=T)
dput(ans)


```

```{r map}
value  <- vector(mode="integer", 10 )
value

f  <- function(x) {
    if (x == 1) {value[[x]] <<- x -1
    return()}
    if (x == 2) {value[[x]] <<- x -1
    return() }

    value[[x]]  <<- value[[x-2]] + value[[x-1]]
}

value  <- sapply(seq_len(9), f )

value
    
```


```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{
file  <- "" 
file  <- basename(file)
file  <- here("rmd", file)
file
}

rmarkdown::render(file,
                  output_format="html_document",
                  output_dir="."
                  )


## replacement for here
if (F) {
  the_dir  <- dirname(file)
  file  <- file.path(the_dir, file)
}


```
