---
title: "064_purrr_basics.Rmd"
output: html_document
---

```{r setup }
knitr::opts_chunk$set(include = FALSE, comment = "     ##")
```



```{r message=FALSE}
library(tidyverse)
library(sloop)
var <- !TRUE
```

```{r test, eval=FALSE, include=FALSE}
print(var)
```

```{r error=TRUE }
quit("stop here")
v <- as.integer(1:3)
class(v) # "integer"
map(v, function(x) x + 2) # list
```

# map_int won't work -- all errors
map_int(v,function(x) x+2)	# Error
map_int(as.integer(v),function(x) x+2)	# Error
map_int(v, ~.x+2)
map_int(1:3, ~.x*3)

#shortcut
map(v, ~.x+2)	# use .x   (not plain x)

```{r}
map_dbl(v, ~ .x + 2) # MUCH BETTER format!
```


```{r}
typeof(mtcars) # list
purrr::map_chr(mtcars, typeof) # each field is double
```

```{r}
v[4] <- NA
v
discard(v, is.na)

v %>%
  discard(is.na)

t <- tibble(a = c(1, 2, 3, NA), b = c(NA, NA, NA, 2))
typeof(t) # "list"
map_chr(t, typeof)

map(t, discard, is.na)
t %>% map(discard, is.na)
```

purrr::transpose
```{r}
r1 <- c("a", "b")
r2 <- c("c", "d")

L <- list(c("a", "b"), c("c", "d"))

typeof(L)

str(L) # list of 2 vectors

M <- purrr::transpose(M)

typeof(M)

str(M) # list of 2 lists ??

M
```

base  object or OO?
3 ways to check
```{r}
is.object(1:10) # FALSE

sloop::otype(1:10) # base

attr(1:10, "class") # NULL

# caution
typeof(1:10) # integer, b/c it is a vector (nothing to do with object)

# caution, misleading, do not use on base objects
class(1:10) # integer??
```
