---
title: "Untitled"
format: html
editor_options: 
  chunk_output_type: console
---

## METACORE  example (SEE: https://atorus-research.github.io/metacore/articles/Example.html )
- make a metacore object
- extract compennts

### An ODM document!  
```{r}
library(metacore)
library(xml2)
doc <- read_xml(metacore_example("SDTM_define.xml"))
xml_ns_strip(doc)
doc
```

### Can not see objects on left,  but they do exist!   (use str())
```{r}
ds_spec2 <- metacore::xml_to_ds_spec(doc)
ds_vars <- xml_to_ds_vars(doc)
var_spec <- xml_to_var_spec(doc)
value_spec <- xml_to_value_spec(doc)
code_list <- xml_to_codelist(doc)
derivations <- xml_to_derivations(doc)
```

### Create a metacore object
```{r}
metacore_obj <- metacore(ds_spec2, ds_vars, var_spec, value_spec, derivations, code_list)
```

### work on "DM"-obj, a subset of metacore object (ds_spec)
```{r}
dm_spec = metacore_obj |> select_dataset("DM")
dm_spec$ds_spec

# this works
glimpse(dm_spec$ds_spec)
glimpse(dm_spec$value_spec)
```

### details for each dataset-variable combo  (var_spec)
```{r}
dm_spec2 = metacore_obj |> select_dataset("DM", simplify=T)
dm_spec2_
glimpse(dm_spec2)

```