---
title: "using easystats notes"
date:  \today 
pdf-engine: lualatex
format:
  html: 
    html-math-method: katex
  pdf: 
    toc: false
    toc_depth:  4   
    number-sections: false
    colorlinks: true
    keep_tex:  false
    include-in-header: 
      text: |
        \usepackage[top=.5in, bottom=.5in, left=.5in, right=.5in]{geometry}
        \usepackage{amsmath,amssymb,amstext,amsfonts}
        \usepackage{lipsum}
        \usepackage{setspace}
#format:
#  pdf: 
#    include-in-header: 
editor_options: 
  chunk_output_type: console
---

\section{To run:}

- quarto preview <file> --to pdf    # (opens in a viewer)
- quarto render %	; zathura         # not quite right cli

- math mode latex,  seems to work if *outside* R chunk
$$
x^2
$$

\section{mtcars has problem}
\code{mtcars} has several numerical columns.
Should be able to write function that takes column name as argument and
computer the mean.

```{r}
f <- function(col) {
  mean(mtcars[[col]])
  #    mean(mtcars$col)
}

f1 <- function(col) {
  mtcars |> mean(col)
}
f2 <- function(col) {
  # mtcars |> mean({{col}})
  mtcars |> mean({
    col
  })
}
f1(mpg)
f1("mpg")
f2(hp)
f2("hp")
f2(quote(hp))
z <- "hp"
f2(z)
```
my_summary <- function(df, grouping_var){
 df %>%
  group_by(grouping_var) %>% 
  summarise(
   avg = mean(air_time),
   sum = sum(air_time),
   min = min(air_time),
   max = max(air_time),
   obs = n()
  )
}
my_summary(airline_df, origin)

subset(mtcars, cyl == 4, select=mpg) 
str(mtcars)
##  Without substitute, R can not find a variable h(mpg) ... ERROR.
##  With substitute, evaluation is paused; 
##  Explaination here:   https://dplyr.tidyverse.org/articles/programming.html
mtcars
names(mtcars)
str(mtcars)


ALL work
```r
h  <- function(col) {
    y  <- substitute(col)
    mean(mtcars[[y]])
    
}
(h("mpg"))
(h(mpg))
(h(hp))

```
```r

# FACT
mtcars |> dplyr::filter(mpg > 20)   # WORKS
mtcars |> dplyr::filter("mpg > 20") # FAILS
e = quote(mpg > 20)

mtcars |> dplyr::filter(e) # FAILS
mtcars |> dplyr::filter(!!e) # WORKS


g <- function(dataset, cond){
    y <- substitute(cond)
    #cat(y, "\n")   # languge, cat can not handle
    cat(deparse(y), "\n")
    dataset |> dplyr::filter(!!cond) #WoRKS
    dataset |> dplyr::filter(eval(cond)) #WoRKS
    #dataset |> dplyr::filter(eval(deparse(y))) #FAILS
    #dataset |> dplyr::filter(deparse(y))   # FAILS
    #dataset |> dplyr::filter(y) # FAILS
    #dataset |> dplyr::filter(eval(y)) # FAILS
    }

g(mtcars, mpg > 20)  # FAILS
g(mtcars, quote(mpg > 20))  # WORKS
?dplyr::filter
```


\section{select a column}
g = function(col) {
    mtcars[[col]]
}
g("mpg")
g(mpg)


\section{explain}

##  substitute: returns expr as name, string as string
##  is a name; not a call, not string
is.call(substitute(col))  #F
is.character(substitute(col)) #F
is.name(substitute(col))   #TRUE

col = "mpg"
substitute(col)  # col
substitute("col") # [1] "col"
substitute(substitute(col)) # substitute(col)


is.name(substitute(col)) #T
## random alpha, returns as name, not character
substitute(abc) # abc
is.name(substitute(abc)) #T
is.character(substitute(abc)) #F

## string returns as string 
substitute("abc")   # character[1]

##  not referencial
identical(col, "mpg") # TRUE
identical(substitute(col), substitute("mpg"))  # FALSE

## b/c
substitute(col)   # col
substitute("mpg") # "mpg"

##  NOTE
is.call(substitute(col))  # F
is.expression(substitute(col))   # F
is.name(substitute(col))   #T
