--- 
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  pdf_document: 
    latex_engine: lualatex
    toc: TRUE 
    toc_depth:  4 
fontsize: 10pt 
geometry: margin=0.4in,top=0.25in 
TAGS:  deparse, substitute
editor_options: 
  chunk_output_type: console
---

REF: https://stackoverflow.com/questions/25235240/r-variable-names-symbols-names-or-something-else/25235365#25235365


####    Symbol, aka name
```{r}
q2  <- quote(x)
is.symbol(q2)
```

#### Coerce to symbol, or name
```{r}
x  <- 4

typeof(x)
is.symbol(x)
is.name(x)
names(x)

is.object(x)   # see ?

# coerce
as.name(x)
as.symbol(x)
identical(as.name(x), as.symbol(x))

ls()
```

#### What is `4`
```{r}
is.object(`4`)
typeof(`4`)
is.symbol(`4`)
```

#### convert to symbol name
```{r}
ls()
y = as.name(x)
y

is.object(y)
typeof(y)
is.symbol(y)
is.name(y)

names(y)
attributes(y)
```

```{r}

## for variable, use as.name
is.symbol(as.name(x))
is.symbol(as.name(x))
is.symbol(quote(x))
identical(as.name(x), quote(x))

eval(y)
eval(`4`)
```



####    cast to vector of type symbol
```{r}
z = as.vector(x, "symbol")
z
is.symbol(z)
is.name(z)
typeof(z)
```

####    Not symbol
```{r not_symbol}
is.symbol(4)

## ??
is.symbol(as.name(4))
z  <- as.name(4)

## weird
is.symbol(z)



##  for function, use quote
f  <- function() {}
is.symbol(quote(f))

is.symbol(f)
## error
if (F) is.symbol(as.name(f))
```



