
---
title: skeleton.qmd
date: last-modified
# Quarto requires title, if want date to appear
# ~/.config/kickstart/skeleton/skeleton.qmd
---
#   TAGS:   

Extremely useful !so
https://stackoverflow.com/questions/46834655/whats-the-difference-between-substitute-and-quote-in-r

In words, quote:      suppresses evaluation of argX
substitute(argX):     substitutes symbol (user provided), no evaluation
argX:                 evalutes !
```{r}
f <- function(argX) {
   list(quote(argX),          # is.symbol = T  ??
        substitute(argX),     # is.symbol is TRUE
        argX)
}
    
suppliedArgX <- 100
f(argX = suppliedArgX)
# [[1]]
# argX
# 
# [[2]]
# suppliedArgX
# 
# [[3]]
# [1] 100

suppliedArgX  <- "hello"
f(argX = suppliedArgX)
quote("hello")
quote(quote("hello"))
quote("hello") |> noquote()
"hello" |> quote() |> noquote()
"hello" |> quote() |> quote() |> noquote()
"hello" |> quote() |> quote() |> noquote() |> noquote()


quote("hello")
eval(quote("hello"))
eval("hello")


```

### quote, eval not inverse
```{r}


quote(2*2) # 2 * 2
eval(quote(2*2)) # [1] 4
quote(eval(2*2)) # eval(2 * 2)
 ```

```{r}
```


vim:linebreak:nospell:nowrap:cul tw=78 fo=tqlnrc foldcolumn=1 cc=+1
