---
output: html_document
editor_options: 
  chunk_output_type: console
---
## REF:   https://www.r-bloggers.com/2019/06/curly-curly-the-successor-of-bang-bang-2/

##    Use columns in df
```{r}
library(dplyr)
library(tibble)

how_many_na <- function(dataframe, column_name){
  dataframe %>%
    dplyr::filter(is.na(column_name)) %>%      # include rows where value in specified column_name is na
    dplyr::count()
}


data(starwars)
head(starwars, n=3L)

# tidyverse triggers error
how_many_na(starwars, "hair_color")

```   

##
# Base R is ok, why?
```{r}

col = "hair_color"
sum(is.na(starwars[, eval(col) ]) )
sum(is.na(starwars[, col ]) )

```

## But this is harder with just Base R [ Exercise]
```{r}

##  Goal:  Given an dataframe, grouping, column  - compute mean of column
summarise_groups <- function(dataframe, grouping_var, column_name){
  dataframe %>%
    group_by(grouping_var) %>%  
    summarise(mean(column_name, na.rm = TRUE))
}

```

##    Tidyverse (pre-bang-bang)
```{r}

summarise_groups <- function(dataframe, grouping_var, column_name){
  grouping_var <- enquo(grouping_var)
  column_name <- enquo(column_name)
  mean_name <- paste0("mean_", quo_name(column_name))

  dataframe %>%
    group_by(!!grouping_var) %>%  
    summarise(!!(mean_name) := mean(!!column_name, na.rm = TRUE))
}
```

Example:  !! injects, not evaluate.  Just inserts code into code.   
Thus we have chance to CHANGE code before actual evaluation.
```r
f = function(ds, col) {
  colname = enquo(col)   # as original
  colname = expr(hp)     # change !
  # dplyr::select, not !!,  evaluates in context of ds; else colname or 'hp' or 'mpg' means nothing
  ds |> dplyr::select(!!(colname))     }

debugonce(f)
f(mtcars, col = expr(mpg) )
```

EXAMPLE:
## Pass a tibble and expr containing criteria (to filter row)
Admiral has this kind of function
```{r}
f = function(ds, criteria) {

   # inside f, possible to manipulate criteria !
    criteria = expr(cyl == 8)

   cat("inside \n")
   # otherwise, apply criteria as user specified
   ds |> dplyr::filter(!!criteria) |> select(1:4)  # unquote
  }


debugonce(f)
f(mtcars, criteria=expr(mpg <20))
```
