project:
  type: website
  render: 
    - "018.2_abstract_syntax_tree.qmd"
    - "!*.R"          # do not render
    - "!*.Rmd"        # do not render 
   
  

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



