--- 
# Spaces, no Tabs
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  pdf_document: 
    latex_engine: xelatex
toc: TRUE 
toc_depth:  1 
fontsize: 12pt 
geometry: margin=0.5in,top=0.25in 
TAGS:  ifelse,switch
---

## base R only,  collect here
*   unlist
*   dput  
*   save

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```

```{r library, include=FALSE		}
library(jimTools)
``` 


if else
```{r if}

# ======================
## if - else if - else
# ======================

f  <- function(x) {
  if (x <0) {cat("less than 0")}
	else if(x<1) {cat("less than 1")}
	else if(x<2) {cat("less than 2")}
	else if(x<3) {cat("less than 3")}
	else if(x<4) {cat("less than 4")}
	else {cat("4 or greater")}
}

x <- -1
f(x)
f(x <- x+1)
f(x  <- x+1)
f(x  <- x+1)
x


#  
# ======================
##		ifelse
# ======================
ifelse(5>3, "yes", "no")


x  <- c(1,5,10)
# return vector of length(x) and each element 'yes' or 'no'
ifelse(x > 5, "yes", "no")  # 'no' 'no' 'yes'

```
### switch
```{r}

x<-2
x  <- "B"
x  <- 3
base::switch(x, "first", 
             B = "second",
             C = "third"
)


choose  <- function(x) {

    base::switch(x, "first", 
             B = "second",
             C = "third",
             x
)

}

x  <- 3
x <- 100
choose(x)
```



