
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  formals, alist, dots 
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

### formals returns unevaluated args as list 
```{r formals}
g  <- function(x) {
}
g()
g(x)
g(3)

formals(g)
```

### alist, like list but does NOT evaluate arguments
```{r alist}
tryCatch (list(x = 2, y = x^2),
          error = function(e) paste0("throws error:", conditionMessage(e))
          )

alist(x = 2, y = x^2)

```

```{r more_alist}


## returns `...` 
  g  <- function(x, y, ... ) {
    dots  <- alist(...)
  }
  (r  <- g(x = 1, y = 2,z=3))

## returns what user submitted
  g.1  <- function(x, y, ...) {
    dots  <- substitute(alist(...))
  }

  (r  <- g.1(x = 1, y = 2, z = 3))


## returns what user submitted, evaluated
g.2  <- function(x, y, ...) {
    dots  <- eval(substitute(alist(...)))
  }
  (r  <- g.2(x = 1, y = 2, z = 3)

```
### dots `...`
```{r dots}
f  <- function(x, y, ...) {
  dots  <- eval(substitute(alist(...)))
  named  <- names(dots)
}

(f(x=3, y=3, z=1))

f  <- function(...) {
  alist(...)
}


s  <- f(x=3)
s
```



### print line numbers (pdf only?)
```{r, attr.source='.numberLines'}
if (TRUE) {
  x <- 1:10
  x + 1
}
```

```{r library 		}
# print all labels
file  <- knitr::current_input() 
print(knitr::all_labels())
library(jimTools)
``` 

```{r style, eval=F, include=F}
# REF  style.tidyverse.org

# args MUST line up
sample_function(
                a = xxxx,
                b = xxxx,
                c = xxxx
                )

# OR
verylongfunctions_indent_like_this(
  a = xxxx,
  b = xxx,
  )

```

```{r knitr::knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```

\newpage


```{r skeleton, include=F, eval=F}
file="/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 
{
file  <- "" 
file  <- basename(file)
file  <- here("rmd", file)
file
}

output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir


rmarkdown::render(file,
    output_format = "pdf_document",
    #output_format = "html_document",
    #output_format=c("html_document", "md_document"),
    output_dir = output_dir)
    #output_file = "out")


```
