
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
---

###  Matrix can be make from int[] and dim !
  *  Adds class automagically
```{r setup, include=FALSE		}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "      ##",
  error = TRUE,
  collapse = TRUE
) # easier to read
```


```{r library 		}
# print all labels
file <- knitr::current_input()
print(knitr::all_labels())
library(jimTools)
``` 

### matrix is a vector? yes
```{r setup}
A <- matrix(c(1, 0, 0, 1), nrow = 2)
A
is.matrix(A)
is.array(A)

class(A)
dput(A)
attributes(A)
```

#### Roll my own matrix?

```{r}
v <- c(1, 0, 0, 1)
is.matrix(v)


# make one change
dim(v) <- c(2L, 2L)
v
is.matrix(v)
attributes(v)
class(v)
```


```{r skeleton}
file <- "/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer
```



