---
output: 
  html:
    toc: true
    html-math-method: katex
    css: styles.css
editor_options: 
  chunk_output_type: console
editor: 
  markdown: 
    wrap: 72
---


::: callout-note
Note that there are five types of callouts, including: `note`,
`warning`, `important`, `tip`, and `caution`.
:::

------------------------------------------------------------------------

## Poisson Distribution

- SEE Taylor, binomial to Poisson 
- BMLS 
- PSU 414 
- wikipedia 
- http://www.econometricsbysimulation.com/search?q=poisson

Let $\chi$ be rv, counting of events , 0, 1, 2 ... per interval. $\chi$ might
be 

- counts per unit time, distance. 
- typos per page. 
- cars passing  per unit time. 
- ATM customers per hour.

## Motivating Poisson:

Suppose, on average, receive 9 letters in mail each day. And suppose can model
post office as poisson. This addresses question: how many letters will I
received today? Then expect sd to be sqrt(9) and so expect actual number of
letters to vary between 3 and 12 (2 sd).


```{=tex}
\begin{align*}
Pr(X = x) = {e^{-\lambda}\lambda^x}/{x!}
\end{align*}
```

```{r} 
lambda = 9    # rate of 1 per unit
x  <- 0:20    # how many counts?
z  <- dpois(x = x, lambda = lambda)
w  <- dpois(x = x, lambda = 1)
plot(z, main ="Poisson Distribution: upto n=20 counts, compare lambda= c(1,9)",
     ylab = "dpois",
     xlab = "counts, 1:n",
     pch = 19,
     col = "plum" 
)
points(w, pch = 20, col="red")   # colors()

# plot(w, main ="Poisson Distribution: upto n=20 counts, lambda=1",
#      ylab = "dpois",
#      xlab = "counts, 1:n",
#      pch = 19,
#      col = 3,
#      col.axis = "5"


```


::: callout-important
Poisson is counting (discrete) probability of  x events in interval.
Each event is random and memoryless.  To answer, how long between events (continuous) use the **Exponential** Distribution.

`warning`, `important`, `tip`, and `caution`.
:::

$\mathbf{E}(\chi) \geqq 1$

###   Typing errors
Suppose on average, we make 3 typos per page.  Find probabily of making more than 1 typo on any given page.

Let $\chi$ be number of errors per page.  Then the rate $\lambda=3$ and both the $\mathbf{E}(\chi)$ and $\mathbf{sd} = 3$

$$
\Pr(\chi \geqq 1) =  1 - \Pr(\chi = 0) 
= 1 - {e^{-3}3^0}/{0!}
0.95
$$