---
title:  "`r knitr::current_input()`"
date: "`r lubridate::today()`"
output:
    html_document:
        toc: true 
        toc_depth: 3
        toc_float: true
font_size: 10
---

https://askgoodquestions.blog/2019/10/07/14-how-confident-are-you-part-1/
```{r BEGIN}
set.seed(1492)

## What does CI (Confidence Interval)  mean?
#  ============================================
## Suppose want to find percentage of students (many) with tatoos
##
## How ?   SAMPLE
p = 0.4  # (usually do not know)
n = 75   # students, sample size
## FACT
## se_bar = sqrt( p_bar * (1 - p_bar)/n)
##

## Take a Sample  (ie string of yes/no, 1,0)
r  <- sample(x = 0:1,
             size = 75,
             replace = TRUE, 
             prob = c(0.6, 0.4))
r
sum(r) #31
(p_bar = sum(r)/n) # [1] 0.4

#####   OR 
# ===========================================
## What does 95% confident actually mean??

## rbinom (n=1, size = 75, prob= 0.4):  ren string of yes/no, 1,0  (size # trials)

## To me:  n=1 means 1 SAMPLE, 
## size=throws in 1 SAMPLE, 
## return is # successes in 1 SAMPLE
##
## n =2 means, return will be 2 values, one for each sample
##
###  FUNCTION
###
 N=75
t  <- tibble::tibble()

##  Theory
##  E[# heads]  = n * p
##  VAR[# heads] = n * p *q
prob = 0.4
n = 75
n*prob # [1] 30
n*prob*(1-prob) # [1] 18

one_sample  <- function(DUMMY = null) {  # 1 sample

    # true value
    prob = 0.4

    # p_bar is percentage heads 
    p_bar  <- rbinom(n=1, size=75, prob = prob)/N

    ## And the range, for any single p_bar, standard error
    se_bar = sqrt( p_bar * (1 - p_bar)/N)
    ## CI
    L  <- p_bar - 1.96*se_bar
    U  <- p_bar + 1.96*se_bar
    contains_TRUE =  (L < prob)   && ( prob < U )
    new  <- tibble::tibble(p_bar = p_bar, L=L, U=U, contains_TRUE = contains_TRUE)
    t <<- rbind(t, new)
    invisible()
}
#   Run experiment many, many times (expected value)
lapply(0:99, one_sample)

# view
t
t[order(t$L), ]
hist(t$p_bar)

print(t, n=100)


nrow(z[!z$contains_TRUE,])
```

## Plot sample estimate with error bars
```{r}
library(ggplot2)
head(t)
(t = t[order(-t$U), ])
t = cbind(t, n= as.integer(rownames(t)))
names(t)
head(t)
ggplot(t, aes(x = L,xend = U,y = n,   , yend =n    )  ) +
  geom_segment(arrow = arrow(length=unit(0.10,"cm"), ends="first", type = "closed")) +
  geom_line(x = .4)
```
```{r}
#   :w
https://ggplot2.tidyverse.org/reference/geom_segment.html
df2 <- expand.grid(
  lineend = c('round', 'butt', 'square'),
  linejoin = c('round', 'mitre', 'bevel'),
  stringsAsFactors = FALSE
)

df2 <- data.frame(df2, y = 1:9)
df2

ggplot(df2, aes(x = 1, y = y, xend = 2, yend = y, label = paste(lineend, linejoin))) +
  geom_segment(
#     lineend = df2$lineend, linejoin = df2$linejoin,
     size = 3, arrow = arrow(length = unit(0.3, "inches"))
  ) +
#  geom_text(hjust = 'outside', nudge_x = -0.2) +
  xlim(0.5, 2)
```


## plots
```{r plot}

file  <- "out"
png(filename = paste0("~/Downloads/print_and_delete/" , file,".png"),
         width = 480, height = 480, units = "px", pointsize = 12,
          bg = "white",  res = NA,
         type = c("cairo", "cairo-png", "Xlib", "quartz")
)

 hist(x)
# boxplot(x, col="green", names=c("UrOx"))

stripchart(x = x, 
           ylim=c(0, 225),
           pch = 1, 
           cex = 0.5,
           frame = TRUE, 
           vertical = TRUE,
           main = "24-hour Ur Ox")

abline(h = 35, col=2)

# plot(x, fake, ylim = c(-5, 5), sub = "t-value = 21.5", type = "p")
# abline(h = fake_mean, col=2)
dev.off()
```


