
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  4   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  
---
~/code/MASTER_INDEX.md

REF:   https://shainarace.github.io/LinearAlgebra/lsapp.html
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

```{r cars}

## 50 obs x 2 var
  str(cars)
 head(cars)


## predict dist to stop v speed?
  plot(cars)

```


#### linear regression
```{r model.matrix}
X  <- model.matrix(dist~speed, data=cars)
X
```


```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{
file  <- "" 
file  <- basename(file)
file  <- here("rmd", file)
file
}




## replacement for here
if (F) {
  the_dir  <- dirname(file)
  file  <- file.path(the_dir, file)
}


```
